name: ci

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  fetchTags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.fetch.outputs.tags }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        id: setupNode
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      -
        if: ${{ steps.setupNode.outputs.cache-hit != 'true' }}
        run: npm install
      -
        id: fetch
        run: node fetch.js
  docker:
    needs: fetchTags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.fetchTags.outputs.tags) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ format('mtaku3/gradient-coder:{0}', matrix.tag) }}
